{
 "title": "New dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "req duration",
   "type": "timeseries",
   "description": " Shows average request duration per endpoint, updated every minute.",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "description": "Real-time RAM usage in MB",
   "gridPos": { "h": 8, "w": 12, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "request for metrics and predict",
   "type": "piechart",
   "description": " Shows the total number of requests per endpoint (like /predict/, /metrics, etc.)",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (handler) (http_requests_total)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "description": "CPU usage of your FastAPI/Streamlit process over time",
   "gridPos": { "h": 7, "w": 12, "x": 9, "y": 8 },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}